language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

# command to install dependencies
install: "pip install -r requirements/travis.txt"

sudo: required

before_script:
  - PW=$(openssl rand -base64 32)
  - sudo useradd guest -p $(perl -e 'print crypt($PW, "salt"),"\n"') -m
  - echo -e "guest\n$PW\nemail@someplace.org" > .django_pam

# command to run tests
script:
  - (cd example_site/settings/; ln -s travis.py local.py)
  - python manage.py migrate
  - make coverage

after_script:
  - sudo userdel -r guest
  - unset PW

after_success:
  coveralls
